In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,100])
print(a)

[  1   2   3   4   5 100]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a.shape

(6,)

In [5]:
b = np.array([[6,7,8,9,10,2000]])
print(b)

[[   6    7    8    9   10 2000]]


In [6]:
b.shape

(1, 6)

In [7]:
b.T

array([[   6],
       [   7],
       [   8],
       [   9],
       [  10],
       [2000]])

In [8]:
np.dot(a,b.T) # dot product of the matrices

array([200130])

In [9]:
np.random.randint(5,9,4)

array([6, 5, 7, 6])

In [10]:
matrix = np.random.randint(60,100,(5,5))
print(matrix)

[[91 79 95 92 94]
 [86 83 89 87 68]
 [67 76 93 89 98]
 [95 75 83 98 97]
 [77 71 90 73 62]]


In [11]:
np.min(matrix)   #gives the minimum element of the matrix

62

In [12]:
np.argmin(matrix) #gives the minimum element index value

24

In [13]:
 b = np.unique(matrix,return_counts=True) #gives the all the  elements in the array one time in array and another array contains the count of the elements

In [14]:
print(b[0])    

[62 67 68 71 73 75 76 77 79 83 86 87 89 90 91 92 93 94 95 97 98]


In [15]:
print(b[1])

[1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 2]


In [16]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'tuple'>


In [17]:
unique_in_a = np.unique(b[1])
unique_in_b = np.unique(b[0])
print(unique_in_a)
print(unique_in_b)

[1 2]
[62 67 68 71 73 75 76 77 79 83 86 87 89 90 91 92 93 94 95 97 98]


In [18]:
idx = np.argmin(b[1])
print(idx)
element = b[0][idx]
print(element)

0
62


In [19]:
# Slicing arrays
matrix

array([[91, 79, 95, 92, 94],
       [86, 83, 89, 87, 68],
       [67, 76, 93, 89, 98],
       [95, 75, 83, 98, 97],
       [77, 71, 90, 73, 62]])

In [20]:
matrix[2:4,1:4]

array([[76, 93, 89],
       [75, 83, 98]])

In [21]:
matrix[0,0]

91